name: Release

on:
  workflow_run:
    workflows: ["Perform Tests"]
    types:
      - completed
  push:
    tags:
      - "*"

jobs:
  release:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main') || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Releasing
        run: |
          echo "creating release"
