name: Release Job

on:
  workflow_call:
    inputs:
      ASDF:
        type: string
        default: "nope"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Releasing
        run: |
          echo "creating release"
          echo "important: $IMPORTANT"
          echo "something: $SOMETHING"
          echo "secret: ${{ secrets.PHANTASM }}"
        env:
          IMPORTANT: ${{ inputs.ASDF }}
          SOMETHING: ${{ github.event.inputs.ASDF }}
